from django.urls import path
from . import views
urlpatterns = [
    path('login/',views.loginPage,name='login'),
    path('register/',views.register,name='register'),
    path('',views.home,name="home"),
    path('settings/',views.setting,name="settings"),
    path('logout/',views.logoutPage,name="logout"),
    path('entry/manuscriptform/',views.manuscriptFormPage, name='manuscriptform'),
    path('entry/languageform/',views.LanguageFormPage,name="languageform"),
    path('entry/generform/',views.GenerFormPage,name='generform'),
    path('entry/reporitoryform/',views.RepositoryFormPage,name="repositoryform"),
    path('entry/repositoryLocationform/',views.RepositoryLocationFormPage,name="repositoryLocationform"),
    path('entry/repositoryOwnerform/',views.RepositoryOwnerFormpage,name="repositoryownerform"),
    path('detail/<int:pk>',views.detail,name="detail"),
    path('edit/<int:pk>',views.edit,name="edit"),
    path('delete/<int:pk>',views.delete, name="delete"),
    path('view/repo/',views.repositoryList, name="repo"),
    path('view/repo/delete_repo/<int:pk>',views.deleteRepo, name="deleteRepo"),
    path('view/genres/',views.genreList, name="genres"),
    path('view/genre/delete_genre/<int:pk>',views.deleteGenre, name="deleteGenre"),
    path('view/owners/',views.OwnerList,name="owners"),
    path('view/owner/delete_owner/<int:pk>',views.deleteOwner, name="deleteOwner"),
    path('view/locations/',views.LocationList,name="locations"),
    path('view/location/delete_location/<int:pk>',views.deleteLocation, name="deleteLocation"),
    path('view/languages/',views.LanguageList,name="languages"),
    path('view/language/delete_language/<int:pk>',views.deleteLanguage, name="deleteLanguage"),
    path('notAllowed',views.notAllowed,name="notAllowed"),
    path("view/genre/editgenre/<int:pk>",views.editGener,name="editGener"),
    path("view/owner/editowner/<int:pk>",views.editOwner,name="editOwner"),
    path("view/repo/editrepo/<int:pk>",views.editRepository,name="editRepo"),
    path("view/location/editlocation/<int:pk>",views.editLocation,name="editLocation"),
    path("view/language/editlanguage/<int:pk>",views.editLanguage,name="editLanguage"),
    path("view/users/",views.users,name="users"),
    path("view/users/editUser/<int:pk>",views.usersEdit,name="edituser"),
    path("view/",views.view,name="view"),
    path("entry/",views.entry,name="entry")
]
