from django.urls import path
from . import views
urlpatterns = [
    path('login/',views.loginPage,name='login'),
    path('register/',views.register,name='register'),
    path('',views.home,name="home"),
    path('settings/',views.setting,name="settings"),
    path('logout/',views.logoutPage,name="logout"),
    path('manuscriptform/',views.manuscriptFormPage, name='manuscriptform'),
    path('languageform/',views.LanguageFormPage,name="languageform"),
    path('generform/',views.GenerFormPage,name='generform'),
    path('reporitoryform/',views.RepositoryFormPage,name="repositoryform"),
    path('repositoryLocationform/',views.RepositoryLocationFormPage,name="repositoryLocationform"),
    path('repositoryOwnerform/',views.RepositoryOwnerFormpage,name="repositoryownerform"),
    path('detail/<int:pk>',views.detail,name="detail"),
    path('edit/<int:pk>',views.edit,name="edit"),
    path('delete/<int:pk>',views.delete, name="delete"),
    path('repo/',views.repositoryList, name="repo"),
    path('delete_repo/<int:pk>',views.deleteRepo, name="deleteRepo"),
    path('genres/',views.genreList, name="genres"),
    path('delete_genre/<int:pk>',views.deleteGenre, name="deleteGenre"),
    path('owners/',views.OwnerList,name="owners"),
    path('delete_owner/<int:pk>',views.deleteOwner, name="deleteOwner"),
    path('locations/',views.LocationList,name="locations"),
    path('delete_location/<int:pk>',views.deleteLocation, name="deleteLocation"),
    path('languages/',views.LanguageList,name="languages"),
    path('delete_language/<int:pk>',views.deleteLanguage, name="deleteLanguage"),
    path('notAllowed',views.notAllowed,name="notAllowed"),
    path("editgenre/<int:pk>",views.editGener,name="editGener"),
    path("editowner/<int:pk>",views.editOwner,name="editOwner"),
    path("editrepo/<int:pk>",views.editRepository,name="editRepo"),
    path("editlocation/<int:pk>",views.editLocation,name="editLocation"),
    path("editlanguage/<int:pk>",views.editLanguage,name="editLanguage"),
]
