# Generated by Django 5.0.1 on 2024-02-18 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('inventor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.inventor')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inventor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.inventor')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('inventor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.inventor')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=255)),
                ('inventor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.inventor')),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inventor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.inventor')),
            ],
        ),
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mansucript_name', models.CharField(max_length=100)),
                ('shelf_mark', models.CharField(max_length=50)),
                ('resp_statement', models.CharField(max_length=50)),
                ('inventory_date', models.DateField(auto_now_add=True)),
                ('measurement', models.CharField(max_length=50)),
                ('follos_number', models.IntegerField()),
                ('binding', models.CharField(max_length=100)),
                ('main_content', models.TextField()),
                ('dating', models.CharField(max_length=50)),
                ('other_provenance', models.CharField(blank=True, max_length=50, null=True)),
                ('scripe', models.CharField(blank=True, max_length=50, null=True)),
                ('no_of_cols', models.IntegerField(blank=True, null=True)),
                ('notes_cur_use', models.TextField(blank=True, null=True)),
                ('no_of_lines', models.IntegerField()),
                ('decoration', models.CharField(max_length=255)),
                ('colophones', models.CharField(max_length=50)),
                ('additional_notes', models.TextField()),
                ('genere', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.genre')),
                ('inventor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.inventor')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.language')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.repository')),
                ('repositoryLocation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.repositorylocation')),
                ('repositoryOwner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.repositoryowner')),
            ],
        ),
    ]
