# Generated by Django 5.0.1 on 2024-01-11 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='inventor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.inventor'),
            preserve_default=False,
        ),
    ]
