# Generated by Django 5.0.1 on 2024-05-19 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuscript',
            old_name='resp_statement',
            new_name='responsiblit_statement',
        ),
    ]
