# Generated by Django 5.0.1 on 2024-05-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_resp_statement_manuscript_responsiblit_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='colophones',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='dating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='decoration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='repositoryOwner',
            field=models.CharField(max_length=255),
        ),
    ]
