# Generated by Django 5.0.1 on 2024-01-11 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_manuscript_inventor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repository',
            name='repositoryLocation',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='repositoryOwner',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='repositoryLocation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.repositorylocation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manuscript',
            name='repositoryOwner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.repositoryowner'),
            preserve_default=False,
        ),
    ]
