# Generated by Django 5.0.1 on 2024-05-20 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_manuscript_colophones_alter_manuscript_dating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repositorylocation',
            old_name='city',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.RemoveField(
            model_name='repository',
            name='description',
        ),
        migrations.RemoveField(
            model_name='repositorylocation',
            name='country',
        ),
    ]
