# Generated by Django 5.0.1 on 2024-05-20 08:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_city_repositorylocation_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuscript',
            old_name='follos_number',
            new_name='folios_number',
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='shelf_mark',
            new_name='shelf_mark_By_Instutition',
        ),
        migrations.RenameField(
            model_name='manuscript',
            old_name='inventory_date',
            new_name='upload_date',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manuscript',
            name='inventor_date',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manuscript',
            name='shelf_mark_By_author',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Inventor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inventor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='inventor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.inventor'),
        ),
    ]
