# Generated by Django 5.0.1 on 2024-05-21 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_follos_number_manuscript_folios_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='author',
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='inventor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
