# Generated by Django 5.0.1 on 2024-05-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_manuscript_author_alter_manuscript_inventor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='language',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='language',
            field=models.ManyToManyField(to='main.language'),
        ),
    ]
