# Generated by Django 5.0.1 on 2024-05-22 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_manuscript_language_manuscript_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='book_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
