# Generated by Django 5.0.1 on 2024-05-28 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_manuscript_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='genere',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='genere',
            field=models.ManyToManyField(to='main.genre'),
        ),
    ]
