# Generated by Django 5.0.1 on 2024-07-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_manuscript_genere_manuscript_genere"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manuscript",
            name="uid",
        ),
        migrations.RemoveField(
            model_name="repository",
            name="uid",
        ),
        migrations.RemoveField(
            model_name="repositoryowner",
            name="uid",
        ),
    ]
