# Generated by Django 5.0.1 on 2024-07-17 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_remove_manuscript_uid_remove_repository_uid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="manuscript",
            name="index",
        ),
    ]
