# Generated by Django 5.0.1 on 2024-07-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_remove_manuscript_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repositoryowner",
            name="index",
        ),
    ]
