# Generated by Django 5.0.1 on 2024-07-18 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_remove_repositoryowner_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="index",
        ),
    ]
