# Generated by Django 5.0.1 on 2024-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_remove_repository_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="folios_number",
            field=models.CharField(max_length=255),
        ),
    ]
