# Generated by Django 5.0.1 on 2024-07-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_manuscript_folios_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="no_of_cols",
            field=models.CharField(max_length=50),
        ),
    ]
