# Generated by Django 5.0.1 on 2024-07-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_alter_manuscript_no_of_cols"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="no_of_cols",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="no_of_lines",
            field=models.CharField(max_length=50),
        ),
    ]
