# Generated by Django 5.0.1 on 2024-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_alter_manuscript_no_of_cols"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="colophones",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="dating",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="measurement",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="no_of_cols",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="no_of_lines",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="other_provenance",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="responsiblit_statement",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="scripe",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="shelf_mark_By_Instutition",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="manuscript",
            name="shelf_mark_By_author",
            field=models.CharField(max_length=255),
        ),
    ]
