# Generated by Django 5.0.1 on 2024-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_alter_manuscript_colophones_alter_manuscript_dating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="main_content",
            field=models.CharField(max_length=255),
        ),
    ]
