# Generated by Django 5.0.1 on 2024-07-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0019_alter_manuscript_main_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="main_content",
            field=models.TextField(max_length=255),
        ),
    ]
