# Generated by Django 5.0.1 on 2024-07-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0021_alter_manuscript_main_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manuscript",
            name="repository",
            field=models.CharField(max_length=255),
        ),
    ]
