# Generated by Django 5.0.1 on 2024-07-19 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_alter_manuscript_repository"),
    ]

    operations = [
        migrations.RenameField(
            model_name="manuscript",
            old_name="manuscript_name",
            new_name="manuscript_title",
        ),
        migrations.RenameField(
            model_name="manuscript",
            old_name="repositoryOwner",
            new_name="repository_owner",
        ),
        migrations.RenameField(
            model_name="manuscript",
            old_name="responsiblit_statement",
            new_name="responsibility_statement",
        ),
    ]
